version: '2'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: openfaceadmin
            PMA_PASSWORD: password
        ports:
            - 8282:80
        networks:
            - openface_network
        depends_on:
            - mariadb

    openface:
        image: gitlab.aporigin.com:5005/3danalec/openface:0.1.0
        environment:
            - 'affinity:container!=~mariadb*' # schedules this container to a node without a container that satisfies mariadb
        ports:
            - 5000:5000
        networks:
            - openface_network
        privileged: true
        depends_on:
            - mariadb
        # migrate DB then execute gunicorn run app with 3 workers and timeout of 12 months
        command: bash -l -c "cd flask && python db.py db init && python db.py db migrate && python db.py db upgrade && gunicorn run:app --timeout 31104000 -k gevent -w 3 -b 0.0.0.0:5000" 

    mariadb:
        image: mariadb:10.0.25
        environment:
            MYSQL_USER: openfaceadmin
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: openfacedb
            MYSQL_ROOT_PASSWORD: password
        ports: 
            - 3306
        networks:
            - openface_network
        volumes:
            - ~/.docker-volumes/openface/mariadb/data:/var/lib/mysql

networks:
    openface_network: