version: '2'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_USER: openfaceadmin
            PMA_PASSWORD: password
        ports:
            - 8383:80
        networks:
            - openface_network
        depends_on:
            - mariadb

    openface:
        build: .
        image: gitlab.aporigin.com:5005/3danalec/openface:0.1.0
        environment:
            - 'affinity:container!=~mariadb*' # schedules this container to a node without a container that satisfies mariadb
        ports:
            - 5000:5000
        networks:
            - openface_network
        volumes:
            - .:/usr/src/openface # only for development, please remove in production 
        privileged: true
        restart: always
        depends_on:
            - mariadb
        command: ['gunicorn', '--chdir', './flask', 'run:app', '--timeout', '31104000', '-k', 'gevent', '-w', '3', '-b', '0.0.0.0:5000'] # gunicorn run app with 3 workers and timeout of 12 months

    mariadb:
        image: mariadb:10.1.16
        environment:
            MYSQL_USER: openfaceadmin
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: openfacedb
            MYSQL_ROOT_PASSWORD: password
        ports: 
            - 3306
        networks:
            - openface_network
        volumes:
            - ~/.docker-volumes/openface/mariadb/data:/var/lib/mysql

networks:
    openface_network: