"""empty message

Revision ID: 08cfaeee6c82
Revises: 30b4007bbc8b
Create Date: 2016-08-16 17:49:06.727763

"""

# revision identifiers, used by Alembic.
revision = '08cfaeee6c82'
down_revision = '30b4007bbc8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('identity', sa.Integer(), nullable=True),
    sa.Column('rep', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_image')
    ### end Alembic commands ###
