"""empty message

Revision ID: 340698530d9f
Revises: ede688d006d2
Create Date: 2016-08-16 18:58:27.455404

"""

# revision identifiers, used by Alembic.
revision = '340698530d9f'
down_revision = 'ede688d006d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('identity', sa.Integer(), nullable=True),
    sa.Column('rep', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_image')
    ### end Alembic commands ###
