"""empty message

Revision ID: def9ad818b51
Revises: None
Create Date: 2016-08-23 14:58:33.211147

"""

# revision identifiers, used by Alembic.
revision = 'def9ad818b51'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('identity', sa.Integer(), nullable=True),
    sa.Column('rep', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('face_image')
    ### end Alembic commands ###
