"""empty message

Revision ID: ede688d006d2
Revises: 08cfaeee6c82
Create Date: 2016-08-16 18:28:51.778954

"""

# revision identifiers, used by Alembic.
revision = 'ede688d006d2'
down_revision = '08cfaeee6c82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phash', sa.String(length=128), nullable=True),
    sa.Column('identity', sa.Integer(), nullable=True),
    sa.Column('rep', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_image')
    ### end Alembic commands ###
